# Generated by Django 3.2.11 on 2022-01-14 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('[ㄱ-힣]', message='한글 이름을 입력해주세요.')])),
                ('Phone_number', models.CharField(db_index=True, help_text='입력예) 042-1234-1234', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}-?\\d{4}$', message='전화번호를 입력해주세요.')])),
                ('memo', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='telephone_book/photo/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사람',
                'verbose_name_plural': '전화번호부',
                'ordering': ['id'],
            },
        ),
    ]
